name: CI

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Blame Alert
        uses: molleer/blame-alert@master
      - name: Hello world
        run: ls -l
