name: CI

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.context.payload.pull_request.base.ref }}
      - name: Blame Alert
        uses: molleer/blame-alert@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
